# ASP.NET Core (BlazorWasm)
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-rc1-014190'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(build.artifactstagingdirectory)'
    